/** @type {import('tailwindcss').Config} */
// Design tokens from the Aya Executive OS system (design/stitch_aya_executive_os/
// executive_operating_system/DESIGN.md). Kept byte-identical to the exported
// Stitch config so screens ported from it render unchanged.
module.exports = {
  content: ['./app/**/*.{js,ts,jsx,tsx,mdx}', './components/**/*.{js,ts,jsx,tsx,mdx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#afcae0',
        'on-surface-variant': '#42474c',
        outline: '#73787c',
        'on-secondary-container': '#007168',
        'on-primary-container': '#819bb0',
        'tertiary-fixed': '#e7deff',
        tertiary: '#1f0d4d',
        'on-primary-fixed-variant': '#304a5b',
        error: '#ba1a1a',
        'on-primary': '#ffffff',
        'surface-dim': '#ccdcf0',
        'surface-tint': '#486174',
        'on-tertiary-container': '#9e8ed3',
        'on-tertiary': '#ffffff',
        'surface-container': '#e3efff',
        'surface-container-highest': '#d4e4f8',
        'on-tertiary-fixed': '#1f0d4e',
        'on-secondary': '#ffffff',
        'secondary-fixed': '#99f3e6',
        'on-error': '#ffffff',
        'on-secondary-fixed-variant': '#005049',
        'outline-variant': '#c2c7cc',
        'error-container': '#ffdad6',
        'on-primary-fixed': '#001e2e',
        'inverse-surface': '#233241',
        'tertiary-container': '#342563',
        'surface-container-high': '#daeafe',
        'primary-container': '#183344',
        'primary-fixed-dim': '#afcae0',
        'secondary-fixed-dim': '#7dd6ca',
        'on-secondary-fixed': '#00201d',
        'primary-fixed': '#cbe6fc',
        'surface-bright': '#f7f9ff',
        'inverse-on-surface': '#e8f1ff',
        'on-error-container': '#93000a',
        primary: '#001e2e',
        surface: '#f7f9ff',
        'on-tertiary-fixed-variant': '#4b3d7b',
        'surface-container-low': '#edf4ff',
        background: '#f7f9ff',
        secondary: '#006a61',
        'on-background': '#0d1d2b',
        'surface-variant': '#d4e4f8',
        'tertiary-fixed-dim': '#cdbdff',
        'secondary-container': '#99f3e6',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#0d1d2b',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-2': '0.125rem',
        'space-4': '0.25rem',
        'space-6': '0.375rem',
        'space-8': '0.5rem',
        'space-12': '0.75rem',
        'space-16': '1rem',
        'space-20': '1.25rem',
        'space-24': '1.5rem',
        'space-32': '2rem',
        'space-40': '2.5rem',
        'space-48': '3rem',
        'space-64': '4rem',
      },
      fontFamily: {
        'label-sm': ['Inter'],
        'tabular-metric': ['Inter'],
        'label-md': ['Inter'],
        'headline-md': ['Inter'],
        'headline-sm': ['Inter'],
        'body-lg': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        display: ['Inter'],
        'body-md': ['Inter'],
        'headline-lg': ['Inter'],
        'tabular-dense': ['Inter'],
        'body-sm': ['Inter'],
      },
      fontSize: {
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.06em', fontWeight: '600' }],
        'tabular-metric': ['28px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '600' }],
        'headline-md': ['22px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        display: ['40px', { lineHeight: '48px', letterSpacing: '-0.025em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'tabular-dense': ['13px', { lineHeight: '16px', letterSpacing: '0em', fontWeight: '500' }],
        'body-sm': ['13px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
